# Generated by Django 6.0.4 on 2026-05-13 17:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0003_codigoverificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='img_portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='marca_agua',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Marca de agua'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='archivo_autorizacion',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Autorización'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='img_portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='img_portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PDF'),
        ),
    ]
