# Generated by Django 6.0.4 on 2026-08-26 15:24

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0004_alter_imagen_img_portada_alter_imagen_marca_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Drive para PDFs grandes (vista previa embed)', max_length=500, null=True, verbose_name='URL de Google Drive'),
        ),
        migrations.AddField(
            model_name='revista',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Drive para PDFs grandes', max_length=500, null=True, verbose_name='URL de Google Drive'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='anio_ingreso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobados', to='biblioartdis.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carnet_frente',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Carnet Frente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carnet_reverso',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Carnet Reverso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_registro',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_restablecer_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL externa del PDF (Google Drive, OneDrive, etc.)', max_length=500, null=True),
        ),
    ]
