# Generated by Django 6.0.4 on 2026-08-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0005_libro_google_drive_url_revista_google_drive_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='google_drive_carnet_frente_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Drive para el carnet frente', max_length=500, null=True, verbose_name='URL Carnet Frente (Google Drive)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_drive_carnet_reverso_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Drive para el carnet reverso', max_length=500, null=True, verbose_name='URL Carnet Reverso (Google Drive)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_drive_matricula_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Drive para la matrícula', max_length=500, null=True, verbose_name='URL Matrícula (Google Drive)'),
        ),
    ]
