# Generated by Django 6.0.4 on 2026-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0006_usuario_google_drive_carnet_frente_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Investigador', 'Investigador (Externo)'), ('Administrador', 'Administrador')], max_length=50),
        ),
    ]
