# Generated by Django 6.0.4 on 2026-09-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0007_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Drive para la imagen', max_length=500, null=True, verbose_name='URL de Google Drive'),
        ),
    ]
