# Generated by Django 6.0.4 on 2026-09-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0008_imagen_google_drive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='google_drive_img_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Drive para la imagen de portada', max_length=500, null=True, verbose_name='URL de Google Drive (Imagen)'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Drive para PDFs grandes', max_length=500, null=True, verbose_name='URL de Google Drive (PDF)'),
        ),
    ]
