# Generated by Django 6.0.4 on 2026-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0009_revista_google_drive_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='archivo_autorizacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='img_portada',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='pdf',
        ),
        migrations.AddField(
            model_name='libro',
            name='google_drive_autorizacion_url',
            field=models.URLField(blank=True, help_text='URL del archivo de autorización en Google Drive', max_length=500, null=True, verbose_name='URL de Autorización (Google Drive)'),
        ),
        migrations.AddField(
            model_name='libro',
            name='google_drive_portada_url',
            field=models.URLField(blank=True, help_text='URL de la imagen de portada en Google Drive', max_length=500, null=True, verbose_name='URL de Portada (Google Drive)'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='URL del PDF en Google Drive (vista previa embed)', max_length=500, null=True, verbose_name='URL de Google Drive (PDF)'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL externa del PDF (alternativa)', max_length=500, null=True),
        ),
    ]
